---
title: "R Workshop -- UT Austin"
author: "Jaime Hsu"
date: "04/../2023"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(srvyr)
library(officer)
library(gtsummary)
library(tidyverse)
library(flextable)
library(patchwork)
library(ghibli)
library(labelled)
library(sjlabelled)


combined <- readRDS("/Users/AntonieHsu/Desktop/combined.Rds")          ## only Taiwan
combined <- combined %>%
  mutate(cola = case_when(YEAR %in% c(1980, 1990) ~ 100, 
                          YEAR == 2000 ~ cola2002, 
                          decade == 2010 ~ cola2008), 
         new_destination = fct_recode(new_destination, "Traditional Destinations" = "traditional", "Other Destinations"= "Others"), 
         decade = ifelse(decade ==2010, "2010-19", decade))%>%
  glimpse()

combined <-combined%>%
  filter(decade == "2010-19")%>%
  select(new_destination, decade, YEAR, PERWT, SEX, CLASSWKR, age, AGE, Education, CITIZEN, married, poverty, EMPSTAT, immigrant_time, inf_adj_wage)%>%
  mutate(poverty = factor(ifelse(poverty==1, "Under Poverty", "Not in Poverty")), 
         citizen = factor(case_when(CITIZEN == "Born abroad of American parents" ~ "Born to American Parents", 
                             CITIZEN == "Naturalized citizen" ~ "Naturalized Citizen", 
                             CITIZEN == "Not a citizen"~ "Not a Citizen", 
                             TRUE~NA_character_)),
       EMPSTAT = factor(case_when(EMPSTAT == "Employed" ~ "Employed", 
                                  EMPSTAT == "Unemployed" ~ "Unemployed", 
                                  EMPSTAT == "Not in labor force" ~ "Not in Labor Force")), 
       EMPSTAT = fct_relevel(EMPSTAT, "Unemployed", "Employed", "Not in Labor Force"),
       CLASSWKR = factor(case_when(CLASSWKR == "Works for wages" ~ "Not Self-Employed", 
                                   CLASSWKR == "Self-employed" ~ "Self-employed")), 
       Education = fct_recode(Education, `More than College` = "Postgrad"),
       immigrant_time = fct_collapse(immigrant_time, `Before 1990` = c("Before 1970", "1970 ~ 1979", 
                                                                       "1980 ~ 1989")))%>%
  rename(`Citizenship Status` = citizen, 
         `Poverty Status` = poverty, 
         `Employment Status` =EMPSTAT, 
         `Self-Employment` =CLASSWKR, 
         `Age Group` =age, 
         `Age` = AGE,
          `Marital Status` =married, 
         `Sex` = SEX,
         `Time of Immigration` = immigrant_time, 
         `Personal Wage` = inf_adj_wage)%>%
  select(-CITIZEN)

combined_wt <- as_survey(combined, weights = PERWT)

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
#############################################################
###    First big descriptive table              ####
############################################################# 



table1 <- survey::svydesign(~1, data = combined, weights = ~ PERWT)%>%
  tbl_svysummary(by = Sex, missing = "no",
                 statistic = list(all_categorical() ~ "{n} ({p}%)", 
                                  c(Age) ~ "{mean} ({sd})", 
                                  c(`Personal Wage`) ~ "{median} ({sd})"),
                 include = c(Age, `Time of Immigration`, Education, `Marital Status`,
                             `Citizenship Status`, `Personal Wage`))%>%
  modify_header(update = list(label ~ "**Variables**"))%>%
  modify_footnote(all_stat_cols() ~ "Weighted N (Weighted Percentages in Parenthesis) for Categorical Variables; Weighted Mean is presented for Age (Standard Deviation in Parenthesis)" )%>%
  bold_labels()%>%
  as_flex_table()%>%
  flextable::add_footer_lines("Data from US Census and ACS")%>%
  flextable::set_caption(caption = "Table 1:Descriptive Table by Sex, Taiwanese Immigrants")%>%
  line_spacing(space = 0.4, part = "body")%>%
  style(pr_t = fp_text(font.family = "serif"), part = "all")

table1



practice_table <- tbl_summary(data = combined, by = Education, missing = "no",
                 statistic = list(all_categorical() ~ "{n} ({p}%)", 
                                  c(Age) ~ "{mean} ({sd})", 
                                  c(`Personal Wage`) ~ "{median} ({sd})"),
                 include = c(Age, Sex, `Time of Immigration`, Education, `Marital Status`,
                             `Citizenship Status`, `Personal Wage`))%>%
  modify_header(update = list(label ~ "**Variables**"))%>%
  modify_footnote(all_stat_cols() ~ "Weighted N (Weighted Percentages in Parenthesis) for Categorical Variables; Weighted Mean is presented for Age (Standard Deviation in Parenthesis)" )%>%
  bold_labels()%>%
  as_flex_table()%>%
  flextable::add_footer_lines("Data from US Census and ACS")%>%
  flextable::set_caption(caption = "Table 2:Descriptive Table by Education, Taiwanese Immigrants")%>%
  line_spacing(space = 0.4, part = "body")%>%
  style(pr_t = fp_text(font.family = "serif"), part = "all")

practice_table


```


```{r for fig2, echo=FALSE, message=FALSE,  fig.asp = 0.5, fig.width = 10, out.width = "120%"}

region_tw <- combined%>%
  mutate(decade = ifelse(decade ==2010, "2010-19", decade), 
         Regions = case_when(STATEICP == "California" ~ "California",
                               REGION == "Middle Atlantic Division" ~ "NY, NJ, PA", 
                               STATEICP == "Texas" ~ "Texas", 
                               TRUE ~ "Others"), 
           Regions = fct_relevel(Regions,  "Texas", "NY, NJ, PA", "Others", "California"))



region_all_wt <- as_survey(region_tw, weights=PERWT)

region_line <- region_all_wt%>%
  group_by(YEAR, bplace, Regions)%>%
  summarize(percentage = survey_mean())%>%
  filter(Regions == "California")%>%
  ggplot(aes(y = percentage, x= YEAR, color=bplace, group =bplace, shape = bplace))+
  geom_line(size = 1)+
  geom_point(size = 2)+
  xlab("Year")+
  ylab("%")+
  theme_minimal()+
  scale_y_continuous(limits= c(0.1, 0.5), labels = scales::label_percent(accuracy = 1L))+
  scale_color_manual(values = c( "Taiwanese" = "#94C5CCFF", "Chinese" = "#5A6F80FF",  "Japanese" = "#F4ADB3FF", "South Korean" = "#ECD89DFF", "Indian" = "#ADB7C0FF"))+
  scale_shape_manual(values = c("Taiwanese" = 15, "Chinese" = 16, "Japanese" = 17, "South Korean" =7, "Indian" =4))
  

region_line+plot_annotation(
   title = "Figure 2: Taiwanese and Asian Immigrants in California from 1980-2019",
  caption = "Data from Census 1980-2000 and ACS 2010-19",
  theme = theme(plot.title = element_text(size = 16, face = "bold"), 
                plot.caption = element_text(size = 14, face = "bold")))& 
   theme(axis.text = element_text(size = 15, face = "bold"),
        axis.title = element_text(size=15, face = "bold"), 
        legend.title = element_blank(),
        legend.text = element_text(size = 15),
        strip.text = element_text(size=14, face = "bold"),
        text = element_text('sans'))
```

```{r for fig1a, echo=FALSE, message=FALSE,  fig.asp = 0.5, fig.width = 10, out.width = "120%"}
n_taiwan<-  combined_wt%>%
  mutate(new_destination = fct_relevel(new_destination, "Traditional Destinations", "Other Destinations"))%>%
  group_by(YEAR, new_destination)%>%
  summarize(prop = survey_mean(), 
            total = srvyr::survey_total(), 
            n = n())%>%
  ggplot(aes(x=YEAR, y= total, color = new_destination))+ 
  geom_line(aes(color=new_destination), size = 1)+
  geom_point(aes(x=YEAR, y= total, color = new_destination), size=2)+
  scale_color_manual(values = c("#94C5CCFF", "#F4ADB3FF"), name = "Destinations", labels = c("Traditional Destinations", "Other Destinations"))+
  ylab("Number of Taiwanese Immigrants")+
  scale_y_continuous(labels = scales::comma)+
  xlab("Year")+
#  scale_x_continuous(breaks = 2010:2021)+
  theme_minimal()

n_taiwan +plot_annotation(
  title = "Figure. 1: Foreign-born Taiwanese Immigrants", 
  caption = "Data from ACS",
  theme = theme(plot.title = element_text(size = 16, face = "bold"), 
                plot.caption = element_text(size = 14, face = "bold")))& 
   theme(axis.text = element_text(size = 15, face = "bold"),
        axis.title = element_text(size=15, face = "bold"), 
        legend.title = element_text(size = 15, face = "bold"),
        legend.text = element_text(size = 15),
        strip.text = element_text(size=14, face = "bold"),
        text = element_text('sans'))



pratice_figure_a<-  combined_wt%>%
  group_by(YEAR, `Citizenship Status`)%>%
  summarize(prop = survey_mean(), 
            n = n())%>%
  ggplot(aes(x=YEAR, y= prop, fill = `Citizenship Status`))+ 
  geom_bar(stat="identity", position = position_fill(reverse = T))+
  xlab("Year")+
# scale_x_continuous(breaks = 2010:2021)+
  ylab("%")+
  scale_y_continuous(labels = scales::percent)+
  theme_minimal()

pratice_figure_b<-  combined_wt%>%
  group_by(YEAR, `Citizenship Status`)%>%
  summarize(prop = survey_mean(), 
            n = n())%>%
  ggplot(aes(x=YEAR, y= prop, fill = `Citizenship Status`))+ 
  geom_area(colour = "black", size = .2, alpha = .4, position = position_fill(reverse = T))+
  xlab("Year")+
# scale_x_continuous(breaks = 2010:2021)+
  ylab("%")+
  scale_y_continuous(labels = scales::percent)+
# scale_fill_grey(start = 0, end = .9)+
  theme_minimal()
  

pratice_figure_a +plot_annotation(
  title = "Figure. 1: Foreign-born Taiwanese Immigrants", 
  caption = "Data from ACS",
  theme = theme(plot.title = element_text(size = 16, face = "bold"), 
                plot.caption = element_text(size = 14, face = "bold")))& 
   theme(axis.text = element_text(size = 15, face = "bold"),
        axis.title = element_text(size=15, face = "bold"), 
        legend.title = element_text(size = 15, face = "bold"),
        legend.text = element_text(size = 15),
        strip.text = element_text(size=14, face = "bold"),
        text = element_text('sans'))


```
